name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_REGISTRY_URL: ghcr.io
  DOCKER_IMAGE_NAME: christoph-kronberger-ebcont-package
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v2
      name: Docker Login GHCR
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.DOCKER_IMAGE_NAME}}
        tags: |
          type=semver,pattern={{version}},value=v1.0.0
          type=raw,enable=true,priority=200,prefix=,suffix=,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}     
